# TOKEN
TOKEN = "Token here"

# USER IDs
OWNERS = [] 
BOT_DEVELOPERS = [] # fill in like ID, ID (415606064856301589, 1469810031229927618)
MODMAIL_USER_ID = 

# ROLE IDs
STAFF_ROLE_ID = 

# CHANNEL IDs
BOT_ERROR_CHANNEL_ID = 
MOD_LOGS_CHANNEL_ID = 
SERVER_LOGS_CHANNEL_ID = 
MESSAGE_LOGS_CHANNEL_ID = 
KILLBOX_CHANNEL_ID = 

# DISCORD LINKS (for modmail)
DISCORD_USER_URL = "https://discord.com/users/"
DISCORD_OAUTH2_LINK = "https://discord.com/oauth2/authorize?client_id="